update basic directory framework

diff --git a/src/basic/verilog/leds/Makefile b/src/basic/verilog/leds/Makefile
--- a/src/basic/verilog/leds/Makefile
+++ b/src/basic/verilog/leds/Makefile
@@ -1,5 +1,5 @@
-filename = switch
-pcf_file = ../../common/io.pcf
+filename = leds
+pcf_file = ../../../common/io.pcf
 
 ICELINK_DIR=$(shell df | grep iCELink | awk '{print $$6}')
 ${warning iCELink path: $(ICELINK_DIR)}
@@ -11,13 +11,12 @@ build:
 
 prog_flash:
 	@if [ -d '$(ICELINK_DIR)' ]; \
-        then \
-            cp $(filename).bin $(ICELINK_DIR); \
-        else \
-            echo "iCELink not found"; \
-            exit 1; \
-    fi
-
+     	then \
+		cp $(filename).bin $(ICELINK_DIR); \
+     	else \
+		echo "iCELink not found"; \
+		exit 1; \
+     	fi
 
 clean:
 	rm -rf $(filename).blif $(filename).asc $(filename).bin
diff --git a/src/basic/verilog/uart_tx/Makefile b/src/basic/verilog/uart_tx/Makefile
--- a/src/basic/verilog/uart_tx/Makefile
+++ b/src/basic/verilog/uart_tx/Makefile
@@ -1,5 +1,5 @@
-filename = leds
-pcf_file = ../../common/io.pcf
+filename = top
+pcf_file = ../../../common/io.pcf
 
 ICELINK_DIR=$(shell df | grep iCELink | awk '{print $$6}')
 ${warning iCELink path: $(ICELINK_DIR)}
@@ -9,14 +9,18 @@ build:
 	arachne-pnr -d 5k -P sg48 -p $(pcf_file) $(filename).blif -o $(filename).asc
 	icepack $(filename).asc $(filename).bin
 
+#prog: #for sram
+	#iceprog -S $(filename).bin
+
 prog_flash:
 	@if [ -d '$(ICELINK_DIR)' ]; \
-     	then \
-		cp $(filename).bin $(ICELINK_DIR); \
-     	else \
-		echo "iCELink not found"; \
-		exit 1; \
-     	fi
+        then \
+            cp $(filename).bin $(ICELINK_DIR); \
+        else \
+            echo "iCELink not found"; \
+            exit 1; \
+    fi
+
 
 clean:
 	rm -rf $(filename).blif $(filename).asc $(filename).bin
